name: Kubevirt build

# On main branch
# on:
#   push:
#     branches:
#       - main

# Test manually
on: workflow_dispatch

jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
            go-version: [ '1.21.x' ]
      steps:
      - run: echo "✔ Checkout code"
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          ref: origin/release-0.59
          repository: kubevirt/kubevirt
          path: kubevirt

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
            go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      - name: Debug
        run: |
            ls
            pwd
            cd kubevirt/
            pwd
            ls

    #   - name: Build binaries
    #     run: make go-all

    #   - run: echo "✔ Build a Docker image. Use Git commit SHA as an Image tag."
    #   - name: Build Docker image
    #     # run: |
    #     # docker build -t docker.io/my-organization/my-app:${{ github.sha }} .
    #     uses: docker/build-push-action@v5
    #     with:
    #       context: ./homeworks/lecture4-devops-programme/
    #       file: ./homeworks/lecture4-devops-programme/Dockerfile
    #       platforms: linux/amd64
    #       push: false
    #       tags: ${{ secrets.DOCKERHUB_USERNAME }}/lab2:${{ github.sha }}

    # deploy:
    #   runs-on: ubuntu-latest
    #   needs: build
    #   steps:
    #   - run: echo "✔ Checkout code"
    #   - name: Checkout code
    #     uses: actions/checkout@v3

    #   - name: Login to Docker Hub
    #     uses: docker/login-action@v3
    #     with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}

    #   - run: echo "✔ Push the built image to your Docker HUB account"
    #   - name: Build Docker image
    #     uses: docker/build-push-action@v5
    #     with:
    #       context: ./homeworks/lecture4-devops-programme/
    #       file: ./homeworks/lecture4-devops-programme/Dockerfile
    #       platforms: linux/amd64
    #       push: true
    #       tags: ${{ secrets.DOCKERHUB_USERNAME }}/lab2:${{ github.sha }}