name: Kubevirt build

# On main branch
# on:
#   push:
#     branches:
#       - main

##TODO: Cache management

# Test manually
on: 
    workflow_dispatch:

jobs:
    build-and-push-images:
      runs-on: ubuntu-latest
      strategy:
        matrix:
            go-version: [ '1.21.x' ]
            platforms: [ 'linux/amd64' ]
      env:
        DOCKERFILE_DIR: "./src/dockerfiles/"
        SUB_PROJECT: "kubevirt"
        API_IMG: "virt-api"
        CONTROLLER_IMG: "controller-api"
        HANDLER_IMG: "handler-api"
        LAUNCHER_IMG: "launcher-api"
        OPERATOR_IMG: "operator-api"
      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Clone from my repo, because of fix (see commits): https://github.com/pre-commit/pre-commit/issues/2722
      - name: Clone Kubevirt PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
            depth: 1
            branch: 'release-0.59'
            owner: 'VikStoykov'
            repository: 'kubevirt'

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
            go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      # - name: Debug
      #   run: |
      #       echo "---= ls =---" && ls
      #       echo "---= pwd =---" && pwd
      #       echo "---= cd to kubevirt dir =---" && cd kubevirt/
      #       echo "---= pwd =---" && pwd
      #       echo "---= ls =---" && ls

      - name: Apply patches
        run: |
          chmod +x ./src/prep-src.sh
          ./src/prep-src.sh
        shell: bash

      - name: Build binaries
        run: |
          cd kubevirt/
          make go-build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker images for ${{ env.API_IMG }} and push them to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_DIR }}${{ env.API_IMG }}.Dockerfile
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SUB_PROJECT }}/${{ env.API_IMG }}:${{ github.sha }}

      - name: Build Docker images for ${{ env.CONTROLLER_IMG }} and push them to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_DIR }}${{ env.CONTROLLER_IMG }}.Dockerfile
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SUB_PROJECT }}/${{ env.CONTROLLER_IMG }}:${{ github.sha }}

      - name: Build Docker images for ${{ env.HANDLER_IMG }} and push them to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_DIR }}${{ env.HANDLER_IMG }}.Dockerfile
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SUB_PROJECT }}/${{ env.HANDLER_IMG }}:${{ github.sha }}

      - name: Build Docker images for ${{ env.LAUNCHER_IMG }} and push them to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_DIR }}${{ env.LAUNCHER_IMG }}.Dockerfile
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SUB_PROJECT }}/${{ env.LAUNCHER_IMG }}:${{ github.sha }}

      - name: Build Docker images for ${{ env.OPERATOR_IMG }} and push them to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_DIR }}${{ env.OPERATOR_IMG }}.Dockerfile
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SUB_PROJECT }}/${{ env.OPERATOR_IMG }}:${{ github.sha }}
