name: Kubevirt build

# On main branch
# on:
#   push:
#     branches:
#       - main

##TODO: Cache management

# Test manually
on: 
    workflow_dispatch:

jobs:
    testing:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run EditorConfig Checker
        uses: editorconfig-checker/action-editorconfig-checker@main

      # This step is in patching of source code
      # - name: Analysing the code with pylint
      #   run: |
      #     pylint --rcfile='homeworks/lecture4-devops-programme/pylintrc' $(git ls-files 'homeworks/lecture4-devops-programme/app/*.py')
      
      - name: Lint with Markdown-lint
        uses: articulate/actions-markdownlint@v1
        with:
          config: .markdownlint.json
          files: 'docs/*.md'
          ignore: node_modules
          #version: 0.28.1

      #- name: Perform gitleaks
      #  uses: zricethezav/gitleaks-action@v2
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    #security-sonar-test:
    #  runs-on: ubuntu-latest
    #  needs: testing
    #  steps:
    #  - run: echo "✔ Checkout code"
    #  - name: Checkout code
    #    uses: actions/checkout@v3
    #  - run: echo "✔ SAST - SonarCloud; Review code smells and security issues"
    #  - name: SonarCloud Scan
    #    uses: sonarsource/sonarcloud-github-action@master
    #    env:
    #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    security-snyk-test:
      runs-on: ubuntu-latest
      needs: testing
      steps:
      - run: echo "✔ Checkout code"
      - name: Checkout code
        uses: actions/checkout@v3

      - run: echo "✔ SCA - Snyk; review security issues"
      - uses: snyk/actions/setup@master
      - name: Snyk code test 
        #if: always()
        # The Snyk Code configuration issues do not use the critical severity level
        run: snyk code test --severity-threshold=high
        #continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    build-and-push-images:
      runs-on: ubuntu-latest
      #needs: [security-sonar-test, security-snyk-test]
      needs: security-snyk-test
      strategy:
        matrix:
            go-version: [ '1.21.x' ]
            platforms: [ 'linux/amd64' ]
      env:
        DOCKERFILE_DIR: "./src/dockerfiles/"
        API_IMG: "virt-api"
        CONTROLLER_IMG: "virt-controller"
        HANDLER_IMG: "virt-handler"
        LAUNCHER_IMG: "virt-launcher"
        OPERATOR_IMG: "virt-operator"
        PUSH: true
      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Clone from my repo, because of fix (see commits): https://github.com/pre-commit/pre-commit/issues/2722
      - name: Clone Kubevirt PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
            depth: 1
            branch: 'release-0.59'
            owner: 'VikStoykov'
            repository: 'kubevirt'

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
            go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      # - name: Debug
      #   run: |
      #       echo "---= ls =---" && ls
      #       echo "---= pwd =---" && pwd
      #       echo "---= cd to kubevirt dir =---" && cd kubevirt/
      #       echo "---= pwd =---" && pwd
      #       echo "---= ls =---" && ls

      - name: Apply patches
        run: |
          chmod +x ./src/prep-src.sh
          ./src/prep-src.sh
        shell: bash

      - name: Build binaries
        run: |
          cd kubevirt/
          make go-build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: echo "Build docker images and push them to Dockerhub"
        if: env.PUSH

      - name: Build api
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_DIR }}${{ env.API_IMG }}.Dockerfile
          platforms: ${{ matrix.platforms }}
          push: ${{ env.PUSH }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.API_IMG }}:${{ github.sha }},${{ secrets.DOCKERHUB_USERNAME }}/${{ env.API_IMG }}:latest

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/${{ env.API_IMG }}:latest'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Build controller
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_DIR }}${{ env.CONTROLLER_IMG }}.Dockerfile
          platforms: ${{ matrix.platforms }}
          push: ${{ env.PUSH }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.CONTROLLER_IMG }}:${{ github.sha }},${{ secrets.DOCKERHUB_USERNAME }}/${{ env.CONTROLLER_IMG }}:latest

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/${{ env.CONTROLLER_IMG }}:latest'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          
      - name: Build handler
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_DIR }}${{ env.HANDLER_IMG }}.Dockerfile
          platforms: ${{ matrix.platforms }}
          push: ${{ env.PUSH }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.HANDLER_IMG }}:${{ github.sha }},${{ secrets.DOCKERHUB_USERNAME }}/${{ env.HANDLER_IMG }}:latest

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/${{ env.HANDLER_IMG }}:latest'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Build launcher
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_DIR }}${{ env.LAUNCHER_IMG }}.Dockerfile
          platforms: ${{ matrix.platforms }}
          push: ${{ env.PUSH }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.LAUNCHER_IMG }}:${{ github.sha }},${{ secrets.DOCKERHUB_USERNAME }}/${{ env.LAUNCHER_IMG }}:latest

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/${{ env.LAUNCHER_IMG }}:latest'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Build operator
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_DIR }}${{ env.OPERATOR_IMG }}.Dockerfile
          platforms: ${{ matrix.platforms }}
          push: ${{ env.PUSH }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.OPERATOR_IMG }}:${{ github.sha }},${{ secrets.DOCKERHUB_USERNAME }}/${{ env.OPERATOR_IMG }}:latest

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/${{ env.OPERATOR_IMG }}:latest'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
