name: Kubevirt build

# On main branch
# on:
#   push:
#     branches:
#       - main

# Test manually
on: 
    workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
            go-version: [ '1.21.x' ]
      steps:
      - run: echo "✔ Checkout code"
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone Kubevirt PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
            depth: 1
            branch: 'release-0.59'
            owner: 'kubevirt'
            repository: 'kubevirt'

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
            go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      - name: Debug
        run: |
            echo "---= ls =---" && ls
            echo "---= pwd =---" && pwd
            echo "---= cd to kubevirt dir =---" && cd kubevirt/
            echo "---= pwd =---" && pwd
            echo "---= ls =---" && ls

      - name: Build binaries
        run: |
          cd kubevirt/
          make go-build

    #   - run: echo "✔ Build a Docker image. Use Git commit SHA as an Image tag."
    #   - name: Build Docker image
    #     # run: |
    #     # docker build -t docker.io/my-organization/my-app:${{ github.sha }} .
    #     uses: docker/build-push-action@v5
    #     with:
    #       context: ./homeworks/lecture4-devops-programme/
    #       file: ./homeworks/lecture4-devops-programme/Dockerfile
    #       platforms: linux/amd64
    #       push: false
    #       tags: ${{ secrets.DOCKERHUB_USERNAME }}/lab2:${{ github.sha }}

    # deploy:
    #   runs-on: ubuntu-latest
    #   needs: build
    #   steps:
    #   - run: echo "✔ Checkout code"
    #   - name: Checkout code
    #     uses: actions/checkout@v3

    #   - name: Login to Docker Hub
    #     uses: docker/login-action@v3
    #     with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}

    #   - run: echo "✔ Push the built image to your Docker HUB account"
    #   - name: Build Docker image
    #     uses: docker/build-push-action@v5
    #     with:
    #       context: ./homeworks/lecture4-devops-programme/
    #       file: ./homeworks/lecture4-devops-programme/Dockerfile
    #       platforms: linux/amd64
    #       push: true
    #       tags: ${{ secrets.DOCKERHUB_USERNAME }}/lab2:${{ github.sha }}