name: Kubevirt build

# On main branch
# on:
#   push:
#     branches:
#       - main

# Test manually
on: 
    workflow_dispatch:

jobs:
    build-and-push-images:
      runs-on: ubuntu-latest
      strategy:
        matrix:
            images: [ 'virt-api', 'virt-controller', 'virt-handler', 'virt-launcher', 'virt-operator' ]
            go-version: [ '1.21.x' ]
            platforms: [ 'linux/amd64' ]
            include:
              - dockerfile: ./src/dockerfiles/virt-api.Dockerfile
                images: virt-api
              - dockerfile: ./src/dockerfiles/virt-controller.Dockerfile
                images: virt-controller
              - dockerfile: ./src/dockerfiles/virt-handler.Dockerfile
                images: virt-handler
              - dockerfile: ./src/dockerfiles/virt-launcher.Dockerfile
                images: virt-launcher
              - dockerfile: ./src/dockerfiles/virt-operator.Dockerfile
                images: virt-operator
      steps:
      - name: Debug ${{ matrix.images }}
        run: echo "${{ matrix.platforms }} - ${{ matrix.dockerfile }} - ${{ matrix.images }}"

      - name: Checkout code
        uses: actions/checkout@v4

      # Clone from my repo, because of fix (see commits): https://github.com/pre-commit/pre-commit/issues/2722
      - name: Clone Kubevirt PUBLIC repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
            depth: 1
            branch: 'release-0.59'
            owner: 'VikStoykov'
            repository: 'kubevirt'

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
            go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      - name: Debug
        run: |
            echo "---= ls =---" && ls
            echo "---= pwd =---" && pwd
            echo "---= cd to kubevirt dir =---" && cd kubevirt/
            echo "---= pwd =---" && pwd
            echo "---= ls =---" && ls

      - name: Apply patches
        run: |
          chmod +x ./src/prep-src.sh
          ./src/prep-src.sh
        shell: bash

      - name: Build binaries
        run: |
          cd kubevirt/
          make go-build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker images for ${{ matrix.platforms }} and push them to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.images }}:${{ github.sha }}

    #   - run: echo "✔ Build a Docker image. Use Git commit SHA as an Image tag."
    #   - name: Build Docker image
    #     # run: |
    #     # docker build -t docker.io/my-organization/my-app:${{ github.sha }} .
    #     uses: docker/build-push-action@v5
    #     with:
    #       context: ./homeworks/lecture4-devops-programme/
    #       file: ./homeworks/lecture4-devops-programme/Dockerfile
    #       platforms: linux/amd64
    #       push: false
    #       tags: ${{ secrets.DOCKERHUB_USERNAME }}/lab2:${{ github.sha }}

    # deploy:
    #   runs-on: ubuntu-latest
    #   needs: build
    #   steps:
    #   - run: echo "✔ Checkout code"
    #   - name: Checkout code
    #     uses: actions/checkout@v3

    #   - name: Login to Docker Hub
    #     uses: docker/login-action@v3
    #     with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_TOKEN }}

    #   - run: echo "✔ Push the built image to your Docker HUB account"
    #   - name: Build Docker image
    #     uses: docker/build-push-action@v5
    #     with:
    #       context: ./homeworks/lecture4-devops-programme/
    #       file: ./homeworks/lecture4-devops-programme/Dockerfile
    #       platforms: linux/amd64
    #       push: true
    #       tags: ${{ secrets.DOCKERHUB_USERNAME }}/lab2:${{ github.sha }}